cc_binary(
    name = "ord_solver",
    srcs = ["ord_solver.cc"],
    deps = [
        "//rlap/cc:factorizers",
        "//rlap/cc:reader",
        "//rlap/cc:types",
        "//rlap/cc:cg",
        "//rlap/cc:preconditioner",
        "//third_party/eigen3"
    ]
)